Repository swift-server/async-http-client, pull requests merged in 2019-09, with the labels that each got.

#98 make sure HTTPClient is shutdown
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🔼 needs-minor-version-bump

#96 Tolerate futures from arbitrary event loops
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: ⚠️ needs-major-version-bump

#94 Add proxy authorization support
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPClientProxyHandler.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🔼 needs-minor-version-bump

#99 give generic parameters nice names
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
Labels: ⚠️ needs-major-version-bump

#103 minor: improve code style
  Package.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#102 EventLoop preference overhaul
  Package.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: ⚠️ needs-major-version-bump

#111 swift 5.1 docker setup
  docker/Dockerfile
  docker/docker-compose.1804.51.yaml
Labels: patch-version-bump-only
