Repository swift-server/async-http-client, pull requests merged in 2021-06, with the labels that each got.

#374 Make DelayOnHeadDelegate resilient
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#379 Fix test for misbehaving server
  Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
  Tests/AsyncHTTPClientTests/SOCKSTestUtils.swift
Labels: needs-no-version-bump

#378 Make Swift 5.2 the minimum required version
  CONTRIBUTING.md
  Package.swift
  README.md
  docker/Dockerfile
  docker/docker-compose.1604.52.yaml
  docker/docker-compose.1804.50.yaml
  docker/docker-compose.1804.51.yaml
  docker/docker-compose.1804.52.yaml
  scripts/check_no_api_breakages.sh
Labels: 🔼 needs-minor-version-bump

#380 Make `testSSLHandshakeErrorPropagation` less flaky
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump

#381 Update NIO family dependencies to 5.2+ versions and fix deprecations
  Package.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/Utils.swift
  Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/SSLContextCacheTests.swift
Labels: patch-version-bump-only

#382 Add http/2 support to HTTPBin
  Package.swift
  Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🔼 needs-minor-version-bump

#377 Refactor Channel creation
  Sources/AsyncHTTPClient/ConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionPool/ChannelHandler/HTTP1ProxyConnectHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/ChannelHandler/SOCKSEventsHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/ChannelHandler/TLSEventsHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Manager.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/HTTPClient+Proxy.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPClientProxyHandler.swift
  Sources/AsyncHTTPClient/Utils.swift
  Tests/AsyncHTTPClientTests/ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTP1ProxyConnectHandlerTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ProxyConnectHandlerTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests.swift
  Tests/AsyncHTTPClientTests/SOCKSEventsHandlerTests+XCTest.swift
  Tests/AsyncHTTPClientTests/SOCKSEventsHandlerTests.swift
  Tests/AsyncHTTPClientTests/TLSEventsHandlerTests+XCTest.swift
  Tests/AsyncHTTPClientTests/TLSEventsHandlerTests.swift
  Tests/LinuxMain.swift
Labels: 🔼 needs-minor-version-bump
