Repository swift-server/async-http-client, pull requests merged in 2021-09, with the labels that each got.

#412 Add a RequestQueue
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Waiter.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+RequestQueue.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+RequestQueueTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+RequestQueueTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+StateTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+WaiterTests.swift
  Tests/LinuxMain.swift
Labels: needs-no-version-bump

#414 Fix doc generation and jazzy version
  docker/Dockerfile
  scripts/generate_docs.sh
Labels: needs-no-version-bump

#413 HTTP1Connections state machine for ConnectionPool
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1ConnectionsTest+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1ConnectionsTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+StateTestUtils.swift
  Tests/LinuxMain.swift
Labels: needs-no-version-bump

#415 [HTTPSchedulableRequest] EventLoop preferences
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+RequestQueueTests.swift
Labels: patch-version-bump-only

#422 Ensure the HTTPConnectionPool calls shutdown on active connections.
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
Labels: patch-version-bump-only

#424 Improve HTTPClient tests
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump

#421 [ConnectionPool] Preserve connection errors
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
Labels: patch-version-bump-only

#425 HTTP1Connection: Close on error while in request
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
Labels: patch-version-bump-only

#426 Fix potentially flaky `HTTPClientTests.testNoBytesSentOverBodyLimit`
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump

#428 Add logging to the new HTTPConnectionPool
  Sources/AsyncHTTPClient/ConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/RequestBag.swift
Labels: patch-version-bump-only

#430 ChannelRead because of closing connection: Remove preconditions
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine+Demand.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
Labels: patch-version-bump-only

#431 Fix HTTP/1.0 support
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
Labels: patch-version-bump-only

#432 Ignore unclean ssl shutdown errors
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/RequestOptions.swift
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+ManagerTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+RequestQueueTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
  Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: patch-version-bump-only

#433 [HTTPConnectionPool] Move Connections down in the file
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
Labels: needs-no-version-bump

#434 [HTTPConnectionPool] Fix timer action races
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
Labels: patch-version-bump-only

#427 [HTTPConnectionPool] Implementation switch
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/RequestBag.swift
  Sources/AsyncHTTPClient/SSLContextCache.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🔼 needs-minor-version-bump

#438 [HTTPConnectionPool] Fix request timer scheduling
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
Labels: patch-version-bump-only

#435 [HTTP1Connection] Add download streaming backpressure test
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
Labels: needs-no-version-bump

#437 [HTTPClient.Configuration] Make connection pool size configurable
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🔼 needs-minor-version-bump

#441 [RequestBag] Fix consumption error in state machine
  Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
  Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: patch-version-bump-only

#442 [HTTP1Connection] Handle 101 Switching Protocols
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
Labels: 🔼 needs-minor-version-bump

#440 [HTTP2ConnectionPool] added `HTTP2Connections` struct
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest.swift
  Tests/LinuxMain.swift
Labels: patch-version-bump-only

#444 Replace tests that depend on `TaskHandler`
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/RequestValidationTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RequestValidationTests.swift
Labels: needs-no-version-bump

#445 prepare `calculateBackoff(failedAttempt:)` to be used in `HTTP2StateMachine`
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+Backoff.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
Labels: patch-version-bump-only

#443 Remove deprecated connection pool
  Sources/AsyncHTTPClient/Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionsState.swift
  Sources/AsyncHTTPClient/HTTPClient+Proxy.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/ResponseReadBuffer.swift
  Sources/AsyncHTTPClient/StringConvertibleInstances.swift
  Sources/AsyncHTTPClient/Utils.swift
  Tests/AsyncHTTPClientTests/ConnectionPoolTests+XCTest.swift
  Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift
  Tests/AsyncHTTPClientTests/ConnectionPoolTestsSupport.swift
  Tests/AsyncHTTPClientTests/ConnectionTests+XCTest.swift
  Tests/AsyncHTTPClientTests/ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/LinuxMain.swift
Labels: patch-version-bump-only
