Repository swift-server/async-http-client, pull requests merged in 2021-11, with the labels that each got.

#463 [HTTP2] Internal `HTTPVersion` configuration
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
Labels: patch-version-bump-only

#465 [HTTP2] Test max streams setting is respected.
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
  Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
Labels: needs-no-version-bump

#466 [HTTP2] Forward HTTP/2 events to `StateMachine`
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
Labels: patch-version-bump-only

#470 Allow NIO HTTPDecoder to correctly support informational responses
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
Labels: needs-no-version-bump

#467 [HTTP2] Basic Integration Tests
  Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/LinuxMain.swift
Labels: needs-no-version-bump

#469 Support informational response heads
  Package.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientInformationalResponsesTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientInformationalResponsesTests.swift
  Tests/LinuxMain.swift
Labels: patch-version-bump-only

#472 Handle NIOSSLError.uncleanShutdown correctly
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/RequestOptions.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientUncleanSSLConnectionShutdownTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientUncleanSSLConnectionShutdownTests.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
  Tests/LinuxMain.swift
Labels: 🔼 needs-minor-version-bump

#471 [HTTP2] More Integration Tests
  Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
Labels: needs-no-version-bump

#473 [HTTP2] Make HTTPVersion public and set to .automatic by default
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
Labels: 🔼 needs-minor-version-bump

#474 [HTTP2] Read Timeout Integration Test
  Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
Labels: needs-no-version-bump

#475 [HTTP2] State in README that we support HTTP/2
  README.md
Labels: 🔼 needs-minor-version-bump

#478 Only crash in debug mode, if HTTPClient was not shutdown
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/Utils.swift
Labels: patch-version-bump-only

#480 Remove redundant `RequestFramingMetadata.Body.none` case
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/RequestFramingMetadata.swift
  Sources/AsyncHTTPClient/RequestValidation.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
  Tests/AsyncHTTPClientTests/RequestValidationTests.swift
Labels: patch-version-bump-only

#486 Fix bug in migration from HTTP1 to HTTP2 and back to HTTP1
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1ConnectionsTest+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1ConnectionsTest.swift
Labels: patch-version-bump-only

#489 Two missing `self`s got past soundness.
  Sources/AsyncHTTPClient/RequestBag.swift
Labels: needs-no-version-bump

#484 Remove a couple of unnecessary imports
  Sources/AsyncHTTPClient/RequestBag.swift
  Sources/AsyncHTTPClient/Utils.swift
Labels: patch-version-bump-only

#479 Always overwrite `Transport-Encoding` and `Content-Length`
  Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/RequestValidation.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/RequestValidationTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RequestValidationTests.swift
Labels: patch-version-bump-only

#483 [Tests] Add some basic IPv6 tests
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump

#490 Fix `bodyLengthMissmatch` error handling
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
Labels: patch-version-bump-only

#495 Run tests in parallel on CI
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#498 Fix flaky tests in `HTTPClientSOCKSTests`
  Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
  Tests/AsyncHTTPClientTests/SOCKSTestUtils.swift
Labels: needs-no-version-bump

#493 Add `XCTAsyncTest` and `XCTAssertThrowsError` from gRPC Swift
  NOTICE.txt
  Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
Labels: patch-version-bump-only

#485 Refactor URL component extraction
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#500 [Tests] Remove XCTAssertNoThrow that wraps XCTAssertEqual
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump
