Repository swift-server/async-http-client, pull requests merged in 2022-02, with the labels that each got.

#549 Disable logging by default and add timeout API
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
Labels: patch-version-bump-only

#550 Fix compilation of tests for Swift 5.5.0/5.5.1
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
Labels: needs-no-version-bump

#551 Add `async` shutdown method to `HTTPClient`
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+shutdown.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  scripts/soundness.sh
Labels: 🔼 needs-minor-version-bump

#552 Make new async/await API public
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+shutdown.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
Labels: 🔼 needs-minor-version-bump

#554 Update README.md for async/await
  README.md
Labels: 🔼 needs-minor-version-bump

#553 Add async/await examples
  Examples/GetHTML/GetHTML.swift
  Examples/GetJSON/GetJSON.swift
  Examples/Package.swift
  Examples/README.md
  Examples/StreamingByteCounter/StreamingByteCounter.swift
Labels: 🔼 needs-minor-version-bump

#555 Crash fix: HTTP2 can handle requests are cancelled
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
Labels: patch-version-bump-only

#557 Use newest `swift-nio` version
  Examples/Package.swift
  Package.swift
Labels: 🔼 needs-minor-version-bump

#556 Add link to examples folder in root README.md
  README.md
Labels: needs-no-version-bump

#558 Crash fix: HTTP2ClientRequestHandler can deal with failing writes
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
Labels: patch-version-bump-only
