Repository swift-server/async-http-client, pull requests merged in 2022-08, with the labels that each got.

#607 Remove the last remaining NIOAtomic
  Sources/AsyncHTTPClient/HTTPClient.swift
Labels: patch-version-bump-only

#609 Don’t call `didReceiveError` twice if deadline is exceeded and request is canceled afterwards
  Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
  Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: patch-version-bump-only

#608 Report last connection error if request deadline is exceeded with async/await API
  Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/Transaction+StateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
Labels: patch-version-bump-only

#610 Support transparent decompression with HTTP/2
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#611 Limit max recursion depth delivering body parts
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#615 Validate missing imports in CI
  docker/docker-compose.2004.main.yaml
  docker/docker-compose.yaml
Labels: needs-no-version-bump

#616 Accurately apply the connect timeout in async code
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
Labels: patch-version-bump-only

#617 Tollerate more data after request body is cancelled
  Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
Labels: patch-version-bump-only

#614 Fix thread leak in `FileDownloadDelegate`
  Sources/AsyncHTTPClient/FileDownloadDelegate.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: patch-version-bump-only

#618 Use NIOCore.System.coreCount for the fileIO thread pool
  Sources/AsyncHTTPClient/HTTPClient.swift
Labels: patch-version-bump-only

#619 NIOFoundationCompat does not appear to be used
  Package.swift
  Package@swift-5.4.swift
  Package@swift-5.5.swift
Labels: patch-version-bump-only

#620 Allow `HTTPClientRequest` to be executed multiple times if `body` is an `AsyncSequence`
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
Labels: patch-version-bump-only

#621 Adopt `Sendable`
  Package.swift
  Package@swift-5.4.swift
  Package@swift-5.5.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Manager.swift
  Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
  Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
  Sources/AsyncHTTPClient/HTTPClient+Proxy.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/SSLContextCache.swift
  Sources/AsyncHTTPClient/UnsafeTransfer.swift
  Sources/AsyncHTTPClient/Utils.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/AsyncTestHelpers.swift
  Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/TransactionTests.swift
Labels: 🔼 needs-minor-version-bump
