Repository swift-server/async-http-client, pull requests merged in 2022-06, with the labels that each got.

#588 Improve errors and testing using NIOTS
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/NIOTransportServices/NWWaitingHandler.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests.swift
Labels: 🔼 needs-minor-version-bump

#591 Fix crash when receiving 2xx response before stream is complete.
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#592 Use a local TCP server that doesn’t accept connections on macOS for `testConnectTimeout()`
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#598 Correctly handle Connection: close with streaming
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: patch-version-bump-only

#599 Correctly close the connection if sendEnd fails
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
Labels: patch-version-bump-only

#594 Add `testSelfSignedCertificateIsRejectedWithCorrectError`
  Package.swift
  Sources/AsyncHTTPClient/NIOTransportServices/NWErrorHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
  Tests/AsyncHTTPClientTests/Resources/self_signed_cert.pem
  Tests/AsyncHTTPClientTests/Resources/self_signed_key.pem
Labels: patch-version-bump-only

#600 Fix flaky Network.framework `testConnectionFailError` test
  Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
Labels: needs-no-version-bump
