Repository swift-server/async-http-client, pull requests merged in 2022-01, with the labels that each got.

#510 Redo HTTP cookie parsing
  Package.swift
  Sources/AsyncHTTPClient/FoundationExtensions.swift
  Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
  Sources/AsyncHTTPClient/Utils.swift
  Sources/CAsyncHTTPClient/CAsyncHTTPClient.c
  Sources/CAsyncHTTPClient/include/CAsyncHTTPClient.h
  Tests/AsyncHTTPClientTests/HTTPClientCookieTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientCookieTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
Labels: patch-version-bump-only

#531 Prepare async/await API for public release
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
  Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/RequestValidation.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
  Tests/AsyncHTTPClientTests/RequestValidationTests.swift
  Tests/AsyncHTTPClientTests/TransactionTests.swift
Labels: 🔼 needs-minor-version-bump

#542 Add 5.6 nightly CI
  docker/docker-compose.2004.56.yaml
Labels: needs-no-version-bump

#545 Print invalid state, if hitting precondition
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
  Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
Labels: patch-version-bump-only

#546 Fix race between connection close and scheduling new request
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
Labels: patch-version-bump-only

#547 Cherry pick: Print invalid state, if hitting precondition (#545)
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
  Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
Labels: patch-version-bump-only

#548 Cherry pick: Fix race between connection close and scheduling new request (#546)
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
Labels: patch-version-bump-only
