Repository swift-server/async-http-client, pull requests merged in 2022-04, with the labels that each got.

#577 Tolerate the request stream being started after .finished
  Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
  Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: patch-version-bump-only

#580 [Redirect] Allow redirect response to have body
  Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: patch-version-bump-only

#583 Add HTTPClientError shortDescription property
  Sources/AsyncHTTPClient/HTTPClient.swift
Labels: 🔼 needs-minor-version-bump

#584 Fix flaky `HTTPClientTests.testResponseDelayGet()` test
  .swiftformat
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump

#566 Call `didSendRequestPart` at the right time
  Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
  Tests/AsyncHTTPClientTests/Mocks/MockRequestExecutor.swift
Labels: patch-version-bump-only
