Repository swift-server/async-http-client, pull requests merged in 2022-10, with the labels that each got.

#634 Add `Hashable` conformance to `HTTPClient.Configuration.Proxy`
  Sources/AsyncHTTPClient/HTTPClient+Proxy.swift
Labels: 🔼 needs-minor-version-bump

#635 Reduce use of `HTTPClient.Configuration` in the Connection objects
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Tests/AsyncHTTPClientTests/EmbeddedChannel+HTTPConvenience.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
Labels: patch-version-bump-only

#636 Add `Hashable` conformance to `HTTPClient.Configuration.HTTPVersion`
  Sources/AsyncHTTPClient/HTTPClient.swift
Labels: 🔼 needs-minor-version-bump

#633 Fix request hang if delegate fails promise returned by `didReceiveBodyPart`
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: patch-version-bump-only

#637 Handle ResponseAccumulator not being able to buffer large response in memory
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🔼 needs-minor-version-bump

#625 Allow immediate request failure on connection error
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
  Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
Labels: patch-version-bump-only

#632 Make `HTTPClientResponse.init` public
  Sources/AsyncHTTPClient/AsyncAwait/AnyAsyncSequence.swift
  Sources/AsyncHTTPClient/AsyncAwait/AsyncLazySequence.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
  Sources/AsyncHTTPClient/AsyncAwait/SingleIteratorPrecondition.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
  Sources/AsyncHTTPClient/AsyncAwait/TransactionBody.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
Labels: 🔼 needs-minor-version-bump

#639 Speedup tests
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/ConnectionPoolSizeConfigValueIsRespectedTests+XCTest.swift
  Tests/AsyncHTTPClientTests/ConnectionPoolSizeConfigValueIsRespectedTests.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientBase.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests.swift
  Tests/AsyncHTTPClientTests/IdleTimeoutNoReuseTests+XCTest.swift
  Tests/AsyncHTTPClientTests/IdleTimeoutNoReuseTests.swift
  Tests/AsyncHTTPClientTests/NoBytesSentOverBodyLimitTests+XCTest.swift
  Tests/AsyncHTTPClientTests/NoBytesSentOverBodyLimitTests.swift
  Tests/AsyncHTTPClientTests/RacePoolIdleConnectionsAndGetTests+XCTest.swift
  Tests/AsyncHTTPClientTests/RacePoolIdleConnectionsAndGetTests.swift
  Tests/AsyncHTTPClientTests/ResponseDelayGetTests+XCTest.swift
  Tests/AsyncHTTPClientTests/ResponseDelayGetTests.swift
  Tests/AsyncHTTPClientTests/StressGetHttpsTests+XCTest.swift
  Tests/AsyncHTTPClientTests/StressGetHttpsTests.swift
  Tests/LinuxMain.swift
Labels: needs-no-version-bump

#640 Replace `NIOSendable` with `Sendable`
  Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
  Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
  Sources/AsyncHTTPClient/HTTPClient+Proxy.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
Labels: patch-version-bump-only

#641 Remove `#if compiler(>=5.5)`
  README.md
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+shutdown.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/SSLContextCache.swift
  Sources/AsyncHTTPClient/UnsafeTransfer.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/AsyncTestHelpers.swift
  Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
  Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
  Tests/AsyncHTTPClientTests/TransactionTests.swift
  Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
Labels: needs-no-version-bump

#643 FileDownloadDelegate: mark `Progress` as `Sendable`
  Sources/AsyncHTTPClient/FileDownloadDelegate.swift
Labels: 🔼 needs-minor-version-bump
