Repository swift-server/async-http-client, pull requests merged in 2023-01, with the labels that each got.

#655 Add Swift 5.8 CI and update nightly CI to Ubuntu 22.04
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  docker/docker-compose.2204.58.yaml
  docker/docker-compose.2204.main.yaml
Labels: needs-no-version-bump

#587 Make Task.logger accessible to delegate implementations outside of Package
  Sources/AsyncHTTPClient/HTTPHandler.swift
Labels: 🔼 needs-minor-version-bump

#658 Add test for HTTP1 request with large header
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1Connection.swift
  Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientBase.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
  Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
  Tests/AsyncHTTPClientTests/Mocks/MockHTTPExecutableRequest.swift
Labels: patch-version-bump-only

#659 Add test for HTTP2 request with large header
  Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump
