Repository swift-server/async-http-client, pull requests merged in 2023-12, with the labels that each got.

#718 Add an idle write timeout
  Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
  Sources/AsyncHTTPClient/ConnectionPool/RequestOptions.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
  Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: 🔼 needs-minor-version-bump

#719 Add missing availability guards in tests
  Sources/AsyncHTTPClient/NIOTransportServices/TLSConfiguration.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientResponseTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
  Tests/AsyncHTTPClientTests/NWWaitingHandlerTests.swift
  Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
  Tests/AsyncHTTPClientTests/TransactionTests.swift
  Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
Labels: needs-no-version-bump

#720 Fix potential race conditions when cancelling read/write idle timers
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
Labels: patch-version-bump-only
