Repository swift-server/async-http-client, pull requests merged in 2024-08, with the labels that each got.

#762 Avoid using deprecated API in tests
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: needs-no-version-bump

#759 mark HTTPClient.Response Sendable
  Sources/AsyncHTTPClient/HTTPHandler.swift
Labels: 🔼 needs-minor-version-bump

#763 Fix OOM issue when setting `concurrentHTTP1ConnectionsPerHostSoftLimit` to `Int.max`
  Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
  Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
Labels: patch-version-bump-only
