Repository swift-server/async-http-client, pull requests merged in 2025-02, with the labels that each got.

#810 fix 5.10 compile on Ubuntu 24.04 (Noble) for Intel (x86_64)
  Sources/AsyncHTTPClient/StructuredConcurrencyHelpers.swift
Labels: 🔨 semver/patch

#812 Remove misuse of EmbeddedEventLoop
  Tests/AsyncHTTPClientTests/HTTPClient+StructuredConcurrencyTests.swift
  Tests/AsyncHTTPClientTests/TransactionTests.swift
Labels: semver/none

#813 Work around Foundation revert
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: semver/none

#811 Add `head` property to `FileDownloadDelegate`'s `Progress`/`Response` struct
  Sources/AsyncHTTPClient/FileDownloadDelegate.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🆕 semver/minor

#816 Add `didVisitURL` delegate method
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/RequestBagTests.swift
Labels: 🆕 semver/minor
