Repository swift-server/async-http-client, pull requests merged in 2025-04, with the labels that each got.

#827 Enable Swift 6.1 jobs in CI
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
Labels: semver/none

#830 Drop support for Swift 5.9
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Package.swift
  README.md
Labels: 🆕 semver/minor

#801 Add "debug initializer" hook for channels
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/HTTPClient.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🆕 semver/minor

#831 Add explicit sendability annotations
  Sources/AsyncHTTPClient/AsyncAwait/AnyAsyncSequence.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
  Sources/AsyncHTTPClient/Base64.swift
  Sources/AsyncHTTPClient/Utils.swift
Labels: 🆕 semver/minor

#833 Fix sendability issues in the connection pool
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
  Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
  Sources/AsyncHTTPClient/NIOLoopBound+Execute.swift
  Tests/AsyncHTTPClientTests/EmbeddedChannel+HTTPConvenience.swift
  Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
  Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests.swift
  Tests/AsyncHTTPClientTests/NWWaitingHandlerTests.swift
  Tests/AsyncHTTPClientTests/TransactionTests.swift
Labels: 🔨 semver/patch

#835 Make body stream writer sendable
  Sources/AsyncHTTPClient/HTTPHandler.swift
Labels: 🆕 semver/minor

#836 Fix a number of sendable warnings in test utilities
  Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
Labels: 🔨 semver/patch

#834 Make the file download delegate sendable
  Sources/AsyncHTTPClient/FileDownloadDelegate.swift
  Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
Labels: 🆕 semver/minor

#839 Clean up Task error handling.
  Sources/AsyncHTTPClient/HTTPClient.swift
  Sources/AsyncHTTPClient/HTTPHandler.swift
  Sources/AsyncHTTPClient/RequestBag.swift
  Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Labels: 🔨 semver/patch

#840 Fix a few more Sendability warnings in Sources
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
  Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
  Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
  Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
Labels: 🆕 semver/minor
